/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MinhasComissoesRouteImport } from './routes/minhas-comissoes'
import { Route as MinhaProgramacaoRouteImport } from './routes/minha-programacao'
import { Route as MeuDashboardRouteImport } from './routes/meu-dashboard'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FanaticosRouteImport } from './routes/fanaticos'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ComissoesEquipeRouteImport } from './routes/comissoes-equipe'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendaEquipeRouteImport } from './routes/agenda-equipe'
import { Route as AcessosRouteImport } from './routes/acessos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendedorSellerIdRouteImport } from './routes/vendedor.$sellerId'
import { Route as FinanceiroGeralRouteImport } from './routes/financeiro.geral'
import { Route as FinanceiroEquipesRouteImport } from './routes/financeiro.equipes'
import { Route as FinanceiroConfigRouteImport } from './routes/financeiro.config'
import { Route as FinanceiroVendedorSellerIdRouteImport } from './routes/financeiro.vendedor.$sellerId'
import { Route as ApiPublicCrmWebhookRouteImport } from './routes/api/public/crm-webhook'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasComissoesRoute = MinhasComissoesRouteImport.update({
  id: '/minhas-comissoes',
  path: '/minhas-comissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaProgramacaoRoute = MinhaProgramacaoRouteImport.update({
  id: '/minha-programacao',
  path: '/minha-programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuDashboardRoute = MeuDashboardRouteImport.update({
  id: '/meu-dashboard',
  path: '/meu-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FanaticosRoute = FanaticosRouteImport.update({
  id: '/fanaticos',
  path: '/fanaticos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ComissoesEquipeRoute = ComissoesEquipeRouteImport.update({
  id: '/comissoes-equipe',
  path: '/comissoes-equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaEquipeRoute = AgendaEquipeRouteImport.update({
  id: '/agenda-equipe',
  path: '/agenda-equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessosRoute = AcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorSellerIdRoute = VendedorSellerIdRouteImport.update({
  id: '/vendedor/$sellerId',
  path: '/vendedor/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroGeralRoute = FinanceiroGeralRouteImport.update({
  id: '/geral',
  path: '/geral',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroEquipesRoute = FinanceiroEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroConfigRoute = FinanceiroConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroVendedorSellerIdRoute =
  FinanceiroVendedorSellerIdRouteImport.update({
    id: '/vendedor/$sellerId',
    path: '/vendedor/$sellerId',
    getParentRoute: () => FinanceiroRoute,
  } as any)
const ApiPublicCrmWebhookRoute = ApiPublicCrmWebhookRouteImport.update({
  id: '/api/public/crm-webhook',
  path: '/api/public/crm-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda-equipe': typeof AgendaEquipeRoute
  '/cadastro': typeof CadastroRoute
  '/comissoes-equipe': typeof ComissoesEquipeRoute
  '/equipe': typeof EquipeRoute
  '/fanaticos': typeof FanaticosRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/meu-dashboard': typeof MeuDashboardRoute
  '/minha-programacao': typeof MinhaProgramacaoRoute
  '/minhas-comissoes': typeof MinhasComissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/financeiro/config': typeof FinanceiroConfigRoute
  '/financeiro/equipes': typeof FinanceiroEquipesRoute
  '/financeiro/geral': typeof FinanceiroGeralRoute
  '/vendedor/$sellerId': typeof VendedorSellerIdRoute
  '/api/public/crm-webhook': typeof ApiPublicCrmWebhookRoute
  '/financeiro/vendedor/$sellerId': typeof FinanceiroVendedorSellerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda-equipe': typeof AgendaEquipeRoute
  '/cadastro': typeof CadastroRoute
  '/comissoes-equipe': typeof ComissoesEquipeRoute
  '/equipe': typeof EquipeRoute
  '/fanaticos': typeof FanaticosRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/meu-dashboard': typeof MeuDashboardRoute
  '/minha-programacao': typeof MinhaProgramacaoRoute
  '/minhas-comissoes': typeof MinhasComissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/financeiro/config': typeof FinanceiroConfigRoute
  '/financeiro/equipes': typeof FinanceiroEquipesRoute
  '/financeiro/geral': typeof FinanceiroGeralRoute
  '/vendedor/$sellerId': typeof VendedorSellerIdRoute
  '/api/public/crm-webhook': typeof ApiPublicCrmWebhookRoute
  '/financeiro/vendedor/$sellerId': typeof FinanceiroVendedorSellerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/agenda-equipe': typeof AgendaEquipeRoute
  '/cadastro': typeof CadastroRoute
  '/comissoes-equipe': typeof ComissoesEquipeRoute
  '/equipe': typeof EquipeRoute
  '/fanaticos': typeof FanaticosRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/marca': typeof MarcaRoute
  '/meu-dashboard': typeof MeuDashboardRoute
  '/minha-programacao': typeof MinhaProgramacaoRoute
  '/minhas-comissoes': typeof MinhasComissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/financeiro/config': typeof FinanceiroConfigRoute
  '/financeiro/equipes': typeof FinanceiroEquipesRoute
  '/financeiro/geral': typeof FinanceiroGeralRoute
  '/vendedor/$sellerId': typeof VendedorSellerIdRoute
  '/api/public/crm-webhook': typeof ApiPublicCrmWebhookRoute
  '/financeiro/vendedor/$sellerId': typeof FinanceiroVendedorSellerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessos'
    | '/agenda-equipe'
    | '/cadastro'
    | '/comissoes-equipe'
    | '/equipe'
    | '/fanaticos'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/marca'
    | '/meu-dashboard'
    | '/minha-programacao'
    | '/minhas-comissoes'
    | '/perfil'
    | '/ranking'
    | '/financeiro/config'
    | '/financeiro/equipes'
    | '/financeiro/geral'
    | '/vendedor/$sellerId'
    | '/api/public/crm-webhook'
    | '/financeiro/vendedor/$sellerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessos'
    | '/agenda-equipe'
    | '/cadastro'
    | '/comissoes-equipe'
    | '/equipe'
    | '/fanaticos'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/marca'
    | '/meu-dashboard'
    | '/minha-programacao'
    | '/minhas-comissoes'
    | '/perfil'
    | '/ranking'
    | '/financeiro/config'
    | '/financeiro/equipes'
    | '/financeiro/geral'
    | '/vendedor/$sellerId'
    | '/api/public/crm-webhook'
    | '/financeiro/vendedor/$sellerId'
  id:
    | '__root__'
    | '/'
    | '/acessos'
    | '/agenda-equipe'
    | '/cadastro'
    | '/comissoes-equipe'
    | '/equipe'
    | '/fanaticos'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/marca'
    | '/meu-dashboard'
    | '/minha-programacao'
    | '/minhas-comissoes'
    | '/perfil'
    | '/ranking'
    | '/financeiro/config'
    | '/financeiro/equipes'
    | '/financeiro/geral'
    | '/vendedor/$sellerId'
    | '/api/public/crm-webhook'
    | '/financeiro/vendedor/$sellerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessosRoute: typeof AcessosRoute
  AgendaEquipeRoute: typeof AgendaEquipeRoute
  CadastroRoute: typeof CadastroRoute
  ComissoesEquipeRoute: typeof ComissoesEquipeRoute
  EquipeRoute: typeof EquipeRoute
  FanaticosRoute: typeof FanaticosRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  MarcaRoute: typeof MarcaRoute
  MeuDashboardRoute: typeof MeuDashboardRoute
  MinhaProgramacaoRoute: typeof MinhaProgramacaoRoute
  MinhasComissoesRoute: typeof MinhasComissoesRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  VendedorSellerIdRoute: typeof VendedorSellerIdRoute
  ApiPublicCrmWebhookRoute: typeof ApiPublicCrmWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-comissoes': {
      id: '/minhas-comissoes'
      path: '/minhas-comissoes'
      fullPath: '/minhas-comissoes'
      preLoaderRoute: typeof MinhasComissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-programacao': {
      id: '/minha-programacao'
      path: '/minha-programacao'
      fullPath: '/minha-programacao'
      preLoaderRoute: typeof MinhaProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-dashboard': {
      id: '/meu-dashboard'
      path: '/meu-dashboard'
      fullPath: '/meu-dashboard'
      preLoaderRoute: typeof MeuDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fanaticos': {
      id: '/fanaticos'
      path: '/fanaticos'
      fullPath: '/fanaticos'
      preLoaderRoute: typeof FanaticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comissoes-equipe': {
      id: '/comissoes-equipe'
      path: '/comissoes-equipe'
      fullPath: '/comissoes-equipe'
      preLoaderRoute: typeof ComissoesEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-equipe': {
      id: '/agenda-equipe'
      path: '/agenda-equipe'
      fullPath: '/agenda-equipe'
      preLoaderRoute: typeof AgendaEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessos': {
      id: '/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/$sellerId': {
      id: '/vendedor/$sellerId'
      path: '/vendedor/$sellerId'
      fullPath: '/vendedor/$sellerId'
      preLoaderRoute: typeof VendedorSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/geral': {
      id: '/financeiro/geral'
      path: '/geral'
      fullPath: '/financeiro/geral'
      preLoaderRoute: typeof FinanceiroGeralRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/equipes': {
      id: '/financeiro/equipes'
      path: '/equipes'
      fullPath: '/financeiro/equipes'
      preLoaderRoute: typeof FinanceiroEquipesRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/config': {
      id: '/financeiro/config'
      path: '/config'
      fullPath: '/financeiro/config'
      preLoaderRoute: typeof FinanceiroConfigRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/vendedor/$sellerId': {
      id: '/financeiro/vendedor/$sellerId'
      path: '/vendedor/$sellerId'
      fullPath: '/financeiro/vendedor/$sellerId'
      preLoaderRoute: typeof FinanceiroVendedorSellerIdRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/api/public/crm-webhook': {
      id: '/api/public/crm-webhook'
      path: '/api/public/crm-webhook'
      fullPath: '/api/public/crm-webhook'
      preLoaderRoute: typeof ApiPublicCrmWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceiroRouteChildren {
  FinanceiroConfigRoute: typeof FinanceiroConfigRoute
  FinanceiroEquipesRoute: typeof FinanceiroEquipesRoute
  FinanceiroGeralRoute: typeof FinanceiroGeralRoute
  FinanceiroVendedorSellerIdRoute: typeof FinanceiroVendedorSellerIdRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroConfigRoute: FinanceiroConfigRoute,
  FinanceiroEquipesRoute: FinanceiroEquipesRoute,
  FinanceiroGeralRoute: FinanceiroGeralRoute,
  FinanceiroVendedorSellerIdRoute: FinanceiroVendedorSellerIdRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessosRoute: AcessosRoute,
  AgendaEquipeRoute: AgendaEquipeRoute,
  CadastroRoute: CadastroRoute,
  ComissoesEquipeRoute: ComissoesEquipeRoute,
  EquipeRoute: EquipeRoute,
  FanaticosRoute: FanaticosRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  MarcaRoute: MarcaRoute,
  MeuDashboardRoute: MeuDashboardRoute,
  MinhaProgramacaoRoute: MinhaProgramacaoRoute,
  MinhasComissoesRoute: MinhasComissoesRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  VendedorSellerIdRoute: VendedorSellerIdRoute,
  ApiPublicCrmWebhookRoute: ApiPublicCrmWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
